#report for curl:
#use Ubuntu 16.04.5
#kcc: version 1.0 GNU-compatibleBuild number: #c9eaccf-1537409156414
if [ -f "hello" ]; then
 rm hello	
fi
kcc -c main.c -o hello
if [ -f "hello" ]; then
 echo "hello is generated by kcc"
 rm hello	
fi
#for comparision 
gcc -c main.c -o hello # will not have error
if [ -f "hello" ]; then
 echo "hello can be generated by gcc"	
fi
